### ISSUE TITLE
Is there any specific plan to support Spark 1.5

### ISSUE THREAD

**Issue by chenliang613** [Huawei-Spark/Spark-SQL-on-HBase#13]
Is there any specific plan to support Spark 1.5

**Comment by ghost** [comment]
We are working on the migration now.

**Comment by xinyunh** [comment]
Hi @chenliang613,

We are working on that. You could check our status on the branch 'spark1.5-alpha'.
And we will notify you when we have finished.

**Comment by chenliang613** [comment]
ok, look forward to the new release.
