### ISSUE TITLE
Detailed Documentation

### ISSUE THREAD

**Issue by rkiyer999** [Huawei-Spark/Spark-SQL-on-HBase#24]
Can I get a detailed documentation of different SQL statements and its usage.
Like :
Does it support view?  
Does it support Index? 
Does it support Stored Procedures?
If yes can I get a syntax. I am looking for usage document if any for testing/evaluating sparksqlonhbase.

**Comment by yzhou2001** [comment]
No support of view nor stored procedure nor index. But HBase really supports sort of "index organized table" and this product supports multidimensional composite primary keys.

**Comment by xinyunh** [comment]
Hi @rkiyer999,

BTW, you might find our documentation under the "doc" folder.
