### ISSUE TITLE
"SparkSQLOnHBase"  support for secure HBase 

### ISSUE THREAD

**Issue by rkiyer999** [Huawei-Spark/Spark-SQL-on-HBase#25]
In the documentation,"SparkSQLOnHBase_v2.2.docx", under limitation section it is mentioned that
"No secure HBase support is in schedule either."

So does it mean that "Spark-SQL-on-Hbase" will not work on Hbase which is kerberized(Secured).Please confirm.

**Comment by yzhou2001** [comment]
It should not work. If one had managed to get it work, it'd not be supported.
