### ISSUE TITLE
Some of the codes that I can't understand

### ISSUE THREAD

**Issue by ccsshh** [Huawei-Spark/Spark-SQL-on-HBase#26]
When I read the part of HBaseSQlParser,the follow code that I can't understand. what the meaning of these?what the use of these?

 protected lazy val insertValues: Parser[LogicalPlan] =
    INSERT ~> INTO ~> TABLE ~> ident ~ (VALUES ~> "(" ~> values <~ ")") ^^ {
      case tableName ~ valueSeq =>
        val valueStringSeq = valueSeq.map { case v =>
          if (v.value == null) null
          else v.value.toString
        }
        InsertValueIntoTableCommand(tableName, valueStringSeq)
    }

  protected lazy val create: Parser[LogicalPlan] =
    CREATE ~> TABLE ~> ident ~
      ("(" ~> tableCols <~ ",") ~
      (PRIMARY ~> KEY ~> "(" ~> keys <~ ")" <~ ")") ~
      (MAPPED ~> BY ~> "(" ~> opt(nameSpace)) ~
      (ident <~ ",") ~
      (COLS ~> "=" ~> "[" ~> expressions <~ "]" <~ ")") ~
      (IN ~> ident).? <~ opt(";") ^^ {

**Comment by xinyunh** [comment]
Hi @ccsshh ,

Please refer http://www.scala-lang.org/api/2.11.7/scala-parser-combinators/#scala.util.parsing.combinator.Parsers
