### ISSUE TITLE
Do you guys have any plans to move this to HBase API 1.0.x?

### ISSUE THREAD

**Issue by atulskulkarni** [Huawei-Spark/Spark-SQL-on-HBase#31]
Hi Folks,

I am curious if you guys have any plans to migrate the HBase version from 0.98.x to HBase 1.0.x? Since this change brings in breaking changes I am curious if there is any effort already made in this direction.

Regards,
Atul.

**Comment by bomeng** [comment]
HBase 1.1 is supported in our 1.1 branch with Spark 1.4, while 1.0.x is compatible with our 0.98 release. Please check it out. Thanks.

**Comment by chenm11** [comment]
maybe later this year 
  
  ------
  
   在2016年2月10日 12:59:38, notifications@github.com写道： 
   
  
    
   
  Closed #31.
